// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_kkAcmBJfD7hszM_3cyk1EksTdwQTPYw',
    appId: '1:484020263911:web:c924a2a2b119707576fb42',
    messagingSenderId: '484020263911',
    projectId: 'uyborapp',
    authDomain: 'uyborapp.firebaseapp.com',
    storageBucket: 'uyborapp.firebasestorage.app',
    measurementId: 'G-J2QKCHQ3BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB20yd7c4u0cW_PKSIeAyQRF5BH340t9cM',
    appId: '1:484020263911:android:5f67c75f4d2e673676fb42',
    messagingSenderId: '484020263911',
    projectId: 'uyborapp',
    storageBucket: 'uyborapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrgXxNJ1APnYb3WwTVSehIv_h_v2f9YMk',
    appId: '1:484020263911:ios:42dbc92b7d2c460c76fb42',
    messagingSenderId: '484020263911',
    projectId: 'uyborapp',
    storageBucket: 'uyborapp.firebasestorage.app',
    iosClientId: '484020263911-8nm6o72ppc3e01fo78m4g4uldvffps46.apps.googleusercontent.com',
    iosBundleId: 'com.example.uyBorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrgXxNJ1APnYb3WwTVSehIv_h_v2f9YMk',
    appId: '1:484020263911:ios:42dbc92b7d2c460c76fb42',
    messagingSenderId: '484020263911',
    projectId: 'uyborapp',
    storageBucket: 'uyborapp.firebasestorage.app',
    iosClientId: '484020263911-8nm6o72ppc3e01fo78m4g4uldvffps46.apps.googleusercontent.com',
    iosBundleId: 'com.example.uyBorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_kkAcmBJfD7hszM_3cyk1EksTdwQTPYw',
    appId: '1:484020263911:web:81ad1d5754b49fc976fb42',
    messagingSenderId: '484020263911',
    projectId: 'uyborapp',
    authDomain: 'uyborapp.firebaseapp.com',
    storageBucket: 'uyborapp.firebasestorage.app',
    measurementId: 'G-42DRG7F7M0',
  );
}
